### ISSUE TITLE
Can't connect via PDP

### ISSUE THREAD

**Issue by oxalorg** [piglet-lang/piglet#1]
I ran

1. `pdp-start-server!` in emacs
2. Ran `bin/piglet --devtools -i piglet:pdp-client`
3. Got the following error

```js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --inspect /Users/ox/projects/piglet/bin/../lib/piglet/node/main.mjs -i piglet:pdp-client`
Debugger listening on ws://127.0.0.1:9229/72c9bec4-38a0-477c-918a-f22d1b1ed988
For help, see: https://nodejs.org/en/docs/inspector
Loading https://piglet-lang.org/packages/piglet:lang: 75.246ms
Loading pdp-client: 33.792ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:17017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/ox/projects/piglet/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:1008:13)
    at ClientRequest.<anonymous> (/Users/ox/projects/piglet/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:856:5)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 17017
}

Node.js v18.16.0
[nodemon] app crashed - waiting for file changes before starting...
```

✅ Confirmed that the websocket server is on:
```
➜  piglet git:(main) ✗ lsof -i :17017
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Emacs   19967   ox   16u  IPv4 0xbcf17be6a06da6df      0t0  TCP localhost:17017 (LISTEN)
```

✅ checking the variable in emacs:
```
pdp--server’s value is #<process websocket server on port 17017>
```

Using a websocket tool called `websocat` gives an error:
```
$ websocat -v ws://localhost:17017
[INFO  websocat::ws_client_peer] get_ws_client_peer
websocat: WebSocketError: I/O failure
websocat: error running
```

But using curl to send an upgrade request works (this also prints PDP conn opened in emacs):

```
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" -H "Sec-WebSocket-Version: 13" http://localhost:17017
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
```

**Comment by plexus** [comment]
For me it looks like this:

```
$ websocat -v ws://localhost:17017
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
```

**Comment by plexus** [comment]
With two `-v`s

```
➜ websocat -vv ws://localhost:17017
[INFO  websocat::lints] Auto-inserting the line mode
[DEBUG websocat] Done third phase of interpreting options.
[DEBUG websocat] Done fourth phase of interpreting options.
[DEBUG websocat] Preparation done. Now actually starting.
[DEBUG websocat::sessionserve] Serving Line2Message(Stdio) to Message2Line(WsClient("ws://localhost:17017/")) with Options { websocket_text_mode: true, websocket_protocol: None, websocket_reply_protocol: None, udp_oneshot_mode: false, udp_broadcast: false, udp_multicast_loop: false, udp_ttl: None, udp_join_multicast_addr: [], udp_join_multicast_iface_v4: [], udp_join_multicast_iface_v6: [], udp_reuseaddr: false, unidirectional: false, unidirectional_reverse: false, max_messages: None, max_messages_rev: None, exit_on_eof: false, oneshot: false, unlink_unix_socket: false, exec_args: [], ws_c_uri: "ws://0.0.0.0/", linemode_strip_newlines: false, linemode_strict: false, origin: None, custom_headers: [], custom_reply_headers: [], websocket_version: None, websocket_dont_close: false, websocket_ignore_zeromsg: false, one_message: false, no_auto_linemode: false, buffer_size: 65536, broadcast_queue_len: 16, read_debt_handling: Warn, linemode_zero_terminated: false, restrict_uri: None, serve_static_files: [], exec_set_env: false, no_exit_on_zeromsg: false, reuser_send_zero_msg_on_disconnect: false, process_zero_sighup: false, process_exit_sighup: false, socks_destination: None, auto_socks5: None, socks5_bind_script: None, tls_domain: None, tls_insecure: false, headers_to_env: [], max_parallel_conns: None, ws_ping_interval: None, ws_ping_timeout: None, request_uri: None, request_method: None, request_headers: [], autoreconnect_delay_millis: 20 }
[DEBUG websocat::stdio_peer] get_stdio_peer (async)
[DEBUG websocat::stdio_peer] Setting stdin to nonblocking mode
[DEBUG websocat::stdio_peer] Installing signal handler
[DEBUG websocat::sessionserve] Underlying connection established
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
```

**Comment by oxalorg** [comment]
Thanks for the help! I figured out the issue.

Apparently `localhost` is resolving to an IPv6 but the websocket.el is specifying a family of `ipv4`. Changing to `127.0.0.1` or `0.0.0.0` while connecting fixes this issue.

Probably because on mac this is my `/etc/hosts`

```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```
